services:
  qaprophet_api:
    image: qaprophet_api
    ports:
      - "8080:8080"
    depends_on:
      - qaprophet_db
      - qaprophet_identity
    build:
      context: .
      dockerfile: QAProphet/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=qaprophet_db;Port=5432;Database=qaDb;User Id=postgres;Password=root;"
      Keycloak__AuthorizationUrl: "http://localhost:18080/realms/qaProphet/protocol/openid-connect/auth"
      Authentication__MetadataAddress: "http://localhost:18080/qaProphet/.well-known/openid-configuration"
      Authentication__ValidIssuer: "http://localhost:18080/qaProphet"
      Authentication__ValidAudience: "account"
  
  qaprophet_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./KeycloakConfiguration/initSchema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: qaDb

  qaprophet_identity:
    image: quay.io/keycloak/keycloak:latest
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://qaprophet_db:5432/qaDb"
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    depends_on:
      - qaprophet_db
    volumes:
      - identity-data:/opt/keycloak/data
      - ./KeycloakConfiguration/qaProphetTheme.jar:/opt/keycloak/providers/qaProphetTheme.jar
      - ./KeycloakConfiguration/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "18080:8080"

volumes:
  db_data:
  identity-data:
